// Версия ProtoBuf

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: assessment_service.proto

// Текущий пакет - указывает пространство имен для сервиса и сообщений. Помогает избегать конфликтов имен.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostLikes_GetLikeCount_FullMethodName = "/assessment_service.PostLikes/GetLikeCount"
)

// PostLikesClient is the client API for PostLikes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PostLikes is service for assessment posts.
type PostLikesClient interface {
	// GetLikeCount returns the likes of the post.
	GetLikeCount(ctx context.Context, in *GetLikeCountRequest, opts ...grpc.CallOption) (*GetLikeCountResponse, error)
}

type postLikesClient struct {
	cc grpc.ClientConnInterface
}

func NewPostLikesClient(cc grpc.ClientConnInterface) PostLikesClient {
	return &postLikesClient{cc}
}

func (c *postLikesClient) GetLikeCount(ctx context.Context, in *GetLikeCountRequest, opts ...grpc.CallOption) (*GetLikeCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLikeCountResponse)
	err := c.cc.Invoke(ctx, PostLikes_GetLikeCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostLikesServer is the server API for PostLikes service.
// All implementations must embed UnimplementedPostLikesServer
// for forward compatibility.
//
// PostLikes is service for assessment posts.
type PostLikesServer interface {
	// GetLikeCount returns the likes of the post.
	GetLikeCount(context.Context, *GetLikeCountRequest) (*GetLikeCountResponse, error)
	mustEmbedUnimplementedPostLikesServer()
}

// UnimplementedPostLikesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostLikesServer struct{}

func (UnimplementedPostLikesServer) GetLikeCount(context.Context, *GetLikeCountRequest) (*GetLikeCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLikeCount not implemented")
}
func (UnimplementedPostLikesServer) mustEmbedUnimplementedPostLikesServer() {}
func (UnimplementedPostLikesServer) testEmbeddedByValue()                   {}

// UnsafePostLikesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostLikesServer will
// result in compilation errors.
type UnsafePostLikesServer interface {
	mustEmbedUnimplementedPostLikesServer()
}

func RegisterPostLikesServer(s grpc.ServiceRegistrar, srv PostLikesServer) {
	// If the following call pancis, it indicates UnimplementedPostLikesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostLikes_ServiceDesc, srv)
}

func _PostLikes_GetLikeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikeCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostLikesServer).GetLikeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostLikes_GetLikeCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostLikesServer).GetLikeCount(ctx, req.(*GetLikeCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostLikes_ServiceDesc is the grpc.ServiceDesc for PostLikes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostLikes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assessment_service.PostLikes",
	HandlerType: (*PostLikesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLikeCount",
			Handler:    _PostLikes_GetLikeCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assessment_service.proto",
}
